services:
  app:
    image: 'day.2-0.0.1:latest'
    container_name: app
    depends_on:
      - db
    ports:
      - '4000:4000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mypostgres
      - SPRING_DATASOURCE_USERNAME=mypostgres
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=mypostgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mypostgres