openapi: 3.0.3
info:
  title: Java API Exercise - Core Criteria
  description: |-
  version: 0.2.2

servers:
  - url: http://localhost:4000
tags:
  - name: examples
paths:
  /signup:
    post:
      tags:
        - users
      summary: Users post
      description: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignup'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signup'
  /signin:
    post:
      tags:
        - users
      summary: Users post
      description: Sign in
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignin'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signin'
  /posts:
    get:
      tags:
        - posts
      summary: Get posts
      description: Get posts by user
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPosts'
    post:
      tags:
        - posts
      summary: Create post
      description: Create new post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePost'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPosts'

components:
  schemas:
    UserSignup:
      type: object
      required: [username, email, password, roles]
      properties:
        username:
          type: string
          example: "hamtar0"
        email:
          type: email
          format: email
          example: "hamtaro@hamhamclub.com"
        password:
          type: string
          example: "password123"
        roles:
          type: array
          items:
            type: string
            example: ["user"]
    Signup:
      type: object
      properties:
        id:
          type: string
          example: "User signed up successfully"
    UserPosts:
      type: object
      properties:
        status:
          type: string
          example: "Success"
        message:
          type: object
          example:
            id:
              type: string
              example: 1
            user:
              type: object
              properties:
                username:
                  type: string
                  example: "hamtar0"
            contents:
              type: string
              example: "I just ate a bunch of sunflowers!"
            postedAt:
              type: string
              example: "2024-02-19T12:00.00+00:00"
    CreatePost:
      type: object
      properties:
        contents:
          type: string
          example: "I just ate a bunch of sunflowers!"
    UserSignin:
      type: object
      properties:
        username:
          type: string
          example: "hamtar0"
        password:
          type: string
          example: "password123"
    Signin:
      type: object
      properties:
        token:
          type: string
          example: "ehijså0aseigya98hy9ap"
        type:
          type: string
          example: "Bearer"
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "hamtar0"
        email:
          type: string
          example: "hamtaro@hamhamclub.com"
        roles:
          type: array
          items:
            type: string
            example: ["ROLE_USER"]