services:
  app:
    image: 'micro-blogging:latest'
    container_name: app
    depends_on:
      - db
    ports:
      - '4000:4000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sadtnrtu
      - SPRING_DATASOURCE_USERNAME=sadtnrtu
      - SPRING_DATASOURCE_PASSWORD=zqTPlsVfGuBe7HCwaI0kaPdB20M281HG
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=sadtnrtu
      - POSTGRES_DATABASE=sadtnrtu
      - POSTGRES_PASSWORD=zqTPlsVfGuBe7HCwaI0kaPdB20M281HG