version: '3.8'

services:
  app:
    image: 'my-secure-app:latest'
    container_name: app
    depends_on:
      - db
    ports:
      - '4000:4000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mypostgresdatabase
      - SPRING_DATASOURCE_USERNAME=mypostgresuser
      - SPRING_DATASOURCE_PASSWORD=mypostgrespassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev

  db:
    image: 'postgres:latest'
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=mypostgresuser
      - POSTGRES_PASSWORD=mypostgrespassword
      - POSTGRES_DB=mypostgresdatabase
    restart: always

volumes:
  db_data:
